blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/AdTecher/.github/blob/main/CONTRIBUTING.md
    about: Check our contributing guide before opening an issue
  - name: Security Vulnerabilities
    url: https://github.com/AdTecher/.github/blob/main/SECURITY.md
    about: Please report security vulnerabilities privately
